language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - WP_VERSION=4.3 WP_MULTISITE=0
  - WP_VERSION=4.2 WP_MULTISITE=0

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer install

script: phpunit
